apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zdrfax9pt-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zdrfax9pt-java-springboot-gitops